#!/bin/bash


DEFAULT_ORACLE_HOME=/usr/lib/oracle/18.3/client64/

DEFAULT_ORACLE_DBA_USER=system
DEFAULT_ORACLE_DBA_USER_PASSWORD=oracle
DEFAULT_SID=mig

DEFAULT_PRECISION100_USER=precision100
DEFAULT_PRECISION100_USER_PASSWORD=Welcome123

DEFAULT_PRECISION100_HOME=$HOME/precision100
DEFAULT_REPO_TYPE="GIT"
DEFAULT_REPO_URL="git@github.com:ennovatenow/precision-100-migration-templates.git"
DEFAULT_PROJECT_NAME=simple-demo

echo "The user should be able to create the '$DEFAULT_PRECISION100_USER' user and give it the"
echo "necessary privileges to create all the constructs" 

read -p "Enter Oracle Home [$DEFAULT_ORACLE_HOME] " INPUT_ORACLE_HOME 
ORACLE_HOME=${INPUT_ORACLE_HOME:-$DEFAULT_ORACLE_HOME}

read -p "Enter Oracle user name [$DEFAULT_ORACLE_DBA_USER]: " INPUT_DBA
ORACLE_DBA_USER=${INPUT_DBA:-$DEFAULT_ORACLE_DBA_USER}

read -p "Enter Oracle user password [$DEFAULT_ORACLE_DBA_USER_PASSWORD]: " INPUT_DBA_PASSWORD
ORACLE_DBA_USER_PASSWORD=${INPUT_DBA_PASSWORD:-$DEFAULT_ORACLE_DBA_USER_PASSWORD}

read -p "Enter Oracle SID [$DEFAULT_SID]: " INPUT_SID
ORACLE_MIG_SID=${INPUT_SID:-$DEFAULT_SID}

read -p "Enter Precision100 Oracle User [$DEFAULT_PRECISION100_USER]: " INPUT_PRECISION100_USER
PRECISION100_USER=${INPUT_PRECISION100_USER:-$DEFAULT_PRECISION100_USER}

read -p "Enter Precision100 Oracle User Password [$DEFAULT_PRECISION100_USER_PASSWORD]: " INPUT_PRECISION100_PASSWORD
PRECISION100_USER_PASSWORD=${INPUT_PRECISION100_PASSWORD:-$DEFAULT_PRECISION100_USER_PASSWORD}

read -p "Enter Precision100 installation folder [$DEFAULT_PRECISION100_HOME]: " INPUT_PRECISION100_FOLDER
PRECISION100_FOLDER=${INPUT_PRECISION100_FOLDER:-$DEFAULT_PRECISION100_HOME}

read -p "Enter Repository Type for the migration templates [$DEFAULT_REPO_TYPE] | FILE: " INPUT_REPO_TYPE
REPO_TYPE=${INPUT_REPO_TYPE:-$DEFAULT_REPO_TYPE}

read -p "Enter Repository URL for the migration templates [$DEFAULT_REPO_URL] " INPUT_REPO_URL
REPO_URL=${INPUT_REPO_URL:-$DEFAULT_REPO_URL}

read -p "Enter migration project name [simple-demo]" INPUT_PROJECT_NAME
PROJECT_NAME=${INPUT_PROJECT_NAME:-$DEFAULT_PROJECT_NAME}

export ORACLE_HOME=/usr/lib/oracle/18.3/client64/
export LD_LIBRARY_PATH="$ORACLE_HOME"/lib
export PATH="$ORACLE_HOME/bin:$PATH"
export TNS_ADMIN="$ORACLE_HOME/lib/network/admin"

export PRECISION100_LOG_FOLDER=$PRECISION100_FOLDER/log
export PRECISION100_OPERATORS_FOLDER=$PRECISION100_FOLDER/operators
export PRECISION100_REPO_OPERATORS_FOLDER=$PRECISION100_FOLDER/repo-operators
export PRECISION100_CONNECTORS_FOLDER=$PRECISION100_FOLDER/connectors
export PRECISION100_CONNECTION="PRECISION100_CONNECTION"

if [ ! -d "$PRECISION100_FOLDER/conf" ]; then
  mkdir -p "$PRECISION100_FOLDER/conf"
fi

if [ ! -d "$PRECISION100_LOG_FOLDER" ]; then
  mkdir -p "$PRECISION100_LOG_FOLDER"
fi

if [ ! -d "$PRECISION100_FOLDER/bin" ]; then
  mkdir -p "$PRECISION100_FOLDER/bin"
fi

if [ ! -d "$PRECISION100_OPERATORS_FOLDER" ]; then
  mkdir -p "$PRECISION100_OPERATORS_FOLDER"
fi

if [ ! -d "$PRECISION100_CONNECTORS_FOLDER" ]; then
  mkdir -p "$PRECISION100_CONNECTORS_FOLDER"
fi

if [ ! -d "$PRECISION100_REPO_OPERATORS_FOLDER" ]; then
  mkdir -p "$PRECISION100_REPO_OPERATORS_FOLDER"
fi

cat > $PRECISION100_FOLDER/conf/.default.env.sh << DEFAULT_ENV
export EXECUTION_NAME=DEFAULT
export PRECISION100_WORK_FOLDER=$PRECISION100_FOLDER
DEFAULT_ENV

#Point .execution.env.sh to .default.env.sh
ln -s $PRECISION100_FOLDER/conf/.default.env.sh $PRECISION100_FOLDER/conf/.execution.env.sh

cat > $PRECISION100_FOLDER/conf/.connections.env.sh << CONNECTIONS
$PRECISION10O_CONNECTION,ORACLE,$PRECISION100_USER,$PRECISION100_USER_PASSWORD,$ORACLE_MIG_SID
CONNECTIONS

cat > $PRECISION100_FOLDER/conf/.oraenv.sh << ORAHOME
export ORACLE_HOME=$ORACLE_HOME
ORAHOME

cat >> $PRECISION100_FOLDER/conf/.oraenv.sh << 'ORAENV'

export LD_LIBRARY_PATH="$ORACLE_HOME"/lib
export PATH="$ORACLE_HOME/bin:$PATH"
export TNS_ADMIN="$ORACLE_HOME/lib/network/admin"

ORAENV

cat >> $PRECISION100_FOLDER/conf/.oraenv.sh << ORASECRET

export USERNAME=$PRECISION100_USER
export PASSWORD=$PRECISION100_USER_PASSWORD
export SID=$ORACLE_MIG_SID

ORASECRET

cat > $PRECISION100_FOLDER/conf/.env.sh << INSTALL_FOLDER

export PRECISION100_FOLDER=$PRECISION100_FOLDER
export PROJECT_NAME=$PROJECT_NAME
export PRECISION100_LOG_FOLDER=$PRECISION100_FOLDER/log
export PRECISION100_OPERATORS_FOLDER=$PRECISION100_FOLDER/operators
export PRECISION100_REPO_OPERATORS_FOLDER=$PRECISION100_FOLDER/repo-operators
export PRECISION100_CONNECTORS_FOLDER=$PRECISION100_FOLDER/connectors
export PRECISION100_CONNECTION="PRECISION100_CONNECTION"

source $PRECISION100_FOLDER/conf/.oraenv.sh
source $PRECISION100_FOLDER/conf/.repo.env.sh

source $PRECISION100_FOLDER/conf/.execution.env.sh

INSTALL_FOLDER

cat >> $PRECISION100_FOLDER/conf/.env.sh << 'ENV'

export REPO_WORK_FOLDER=$PRECISION100_WORK_FOLDER/git-local
export PRECISION100_LOG_FOLDER=$PRECISION100_WORK_FOLDER/log
export PRECISION100_OPERATORS_FOLDER=$PRECISION100_FOLDER/operators
export PRECISION100_CONNECTORS_FOLDER=$PRECISION100_FOLDER/connectors
export PRECISION100_CONNECTION="PRECISION100_CONNECTION"

export CONTAINER_FOLDER="$REPO_WORK_FOLDER/$PROJECT_FOLDER/containers"
export PIPELINE_FOLDER="$REPO_WORK_FOLDER/$PROJECT_FOLDER/pipelines"
export DATAFLOW_FOLDER="$REPO_WORK_FOLDER/$PROJECT_FOLDER/dataflows"

export SIMULATION_MODE=FALSE
export SIMULATION_SLEEP=2

ENV

cat > $PRECISION100_FOLDER/conf/.repo.env.sh << REPOENV

export REPO_URL=$REPO_URL
export PROJECT_FOLDER=$PROJECT_NAME
export REPO_TYPE=$REPO_TYPE

REPOENV

$ORACLE_HOME/bin/sqlplus -s /nolog << EOF 1> >(tee -a $PRECISION100_LOG_FOLDER/sqlerr.log) 2> >(tee -a $PRECISION100_LOG_FOLDER/sqlerr.log >&2)
SET FEED OFF
CONNECT $ORACLE_DBA_USER/$ORACLE_DBA_USER_PASSWORD@$ORACLE_MIG_SID
CREATE USER $PRECISION100_USER IDENTIFIED BY "$PRECISION100_USER_PASSWORD";
GRANT CONNECT TO $PRECISION100_USER;
GRANT CONNECT, RESOURCE, DBA TO $PRECISION100_USER;
GRANT CREATE SESSION TO $PRECISION100_USER;
GRANT ALL PRIVILEGE TO $PRECISION100_USER;
GRANT UNLIMITED TABLESPACE TO $PRECISION100_USER;
exit;
EOF

$ORACLE_HOME/bin/sqlplus -s /nolog << FILE_LIST 1> >(tee -a $PRECISION100_LOG_FOLDER/sqlerr.log) 2> >(tee -a $PRECISION100_LOG_FOLDER/sqlerr.log >&2)
SET FEED OFF
connect $PRECISION100_USER/$PRECISION100_USER_PASSWORD@$ORACLE_MIG_SID
@install/sql/PERFORMANCE_LOGS.sql
@install/sql/PROGRESS_LOGS.sql
@install/sql/O_TAB_COLUMNS.sql
@install/sql/TRANSFORM_INTERCEPTOR.sql
@install/sql/MAP_CODES.sql
exit;
FILE_LIST
 
cp ./install/bin/*.sh $PRECISION100_FOLDER/bin
cp ./install/conf/.*.sh $PRECISION100_FOLDER/conf
cp -R ./install/operators/* $PRECISION100_OPERATORS_FOLDER
cp -R ./install/repo-operators/* $PRECISION100_REPO_OPERATORS_FOLDER
cp -R ./install/connectors/* $PRECISION100_CONNECTORS_FOLDER
cp ./install/*.sh $PRECISION100_FOLDER
