
export OPERATOR_FOLDER="$PRECISION100_OPERATORS_FOLDER/length-validator"
export LENGTH_VALIDATOR_WORK_FOLDER="$PRECISION100_WORK_FOLDER/length-validator/work"
export DEFAULT_VIEW_NAME_SUFFIX="L"
export DEFAULT_VIEW_NAME_PREFIX="V"

