DROP TABLE MAP_CODES;
CREATE TABLE MAP_CODES(
  CODE_TYPE      NVARCHAR2(50),
  LEG_CODE       NVARCHAR2(100),
  LEG_CODE_DESC  NVARCHAR2(500),
  DEST_CODE      NVARCHAR2(100),
  DEST_CODE_DESC NVARCHAR2(500),
  IS_DEFAULT	 NVARCHAR(1)
);
CREATE OR REPLACE FUNCTION CONVERT_CODES(
   CODE_TYPE_IN IN NVARCHAR2 ,  
   LEGACY_CODE_IN IN NVARCHAR2
  ) RETURN NVARCHAR2 IS
    FIN_CODE_RET NVARCHAR2(100);
    DEF_FIN_CODE_RET NVARCHAR2(100) := '';
BEGIN
   SELECT FIN_CODE 
   INTO   DEF_FIN_CODE_RET 
   FROM   MAP_CODES 
   WHERE  CODE_TYPE = CODE_TYPE_IN 
   AND    IS_DEFAULT = 'Y';

   SELECT FIN_CODE 
   INTO   FIN_CODE_RET 
   FROM   MAP_CODES 
   WHERE  CODE_TYPE = CODE_TYPE_IN 
   AND    LEG_CODE = LEGACY_CODE_IN;

   RETURN FIN_CODE_RET;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN DEF_FIN_CODE_RET;
END;
/

