DROP TABLE MAP_OFF_ACC;
CREATE TABLE MAP_OFF_ACC (
  LEG_ACC_NUM NVARCHAR2(50), 
  LEG_ACCT_TYPE NVARCHAR2(50), 
  LEG_GL_SUB_HEAD NVARCHAR2(50),
  LEG_CCY NVARCHAR2(3),
  LEG_ATTRIBUTE1 NVARCHAR2(50), 
  LEG_ATTRIBUTE2 NVARCHAR2(50), 
  LEG_ATTRIBUTE3 NVARCHAR2(50), 
  LEG_ATTRIBUTE4 NVARCHAR2(50), 
  LEG_ATTRIBUTE5 NVARCHAR2(50), 
  LEG_ATTRIBUTE6 NVARCHAR2(50), 
  LEG_ATTRIBUTE7 NVARCHAR2(50), 
  LEG_ATTRIBUTE8 NVARCHAR2(50),     
  LEG_ATTRIBUTE9 NVARCHAR2(50), 
  LEG_ATTRIBUTE10 NVARCHAR2(50),     
  DEST_ACC_NUM NVARCHAR2(50), 
  DEST_BRANCH_ID NVARCHAR2(50), 
  DEST_PROD_CODE NVARCHAR2(50), 
  DEST_PROD_TYPE NVARCHAR2(50), 
  DEST_GL_SUB_HEAD NVARCHAR2(50)
);
