CREATE OR REPLACE PROCEDURE TRANSFORM_INTERCEPTOR(EVENT VARCHAR2, TABLE_NAME VARCHAR2) AS 
   L_PROCEDURE_EXISTS VARCHAR2(1) := 'Y';
   L_STATEMENT VARCHAR2(1000) := 'BEGIN '||EVENT||'_'||TABLE_NAME||'; END;';
BEGIN 
  SELECT '1' 
  INTO   L_PROCEDURE_EXISTS
  FROM   USER_PROCEDURES
  WHERE  PROCEDURE_NAME = TABLE_NAME;
  
  PROGRESS_LOGS_PKG.LOG('TRANSFORM_INTERCEPTOR',EVENT,'INVOKING: '||L_STATEMENT);
  EXECUTE IMMEDIATE L_STATEMENT;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    PROGRESS_LOGS_PKG.LOG('TRANSFORM_INTERCEPTOR',EVENT,'NO CUSTOM PROCEDURE CREATED FOR TABLE: '||TABLE_NAME);
END;
/
