
export MAP_FILE_WORK_FOLDER=$PRECISION100_WORK_FOLDER/map-file/work
export MAP_FILE_FILE_SUFFIX="csv"

export DEFAULT_TABLE_NAME_PREFIX="O"
export DEFAULT_TAB_COLUMN_SUFFIX="tab-column"
export DEFAULT_TRANSFORM_SUFFIX="transform"
export DEFAULT_COLUMN_DATA_TYPE="NVARCHAR2(2000)"

export DEFAULT_COLUMN_NAME_INDEX="1"
export DEFAULT_DATA_TYPE_INDEX="2"
export DEFAULT_MAX_LENGTH_INDEX="4"
export DEFAULT_MAPPING_TYPE_INDEX="7"
export DEFAULT_MAPPING_VALUE_INDEX="8"
export DEFAULT_MAPPING_COLUMN_INDEX="6"
