export OPERATOR_HOME="$PRECISION100_OPERATORS_FOLDER/sql-plus"
export ORACLE_HOME=$ORACLE_HOME
export LD_LIBRARY_PATH="$ORACLE_HOME"/lib
export PATH="$ORACLE_HOME/bin:$PATH"
export TNS_ADMIN="$ORACLE_HOME/lib/network/admin"
